import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { PlayerProvider } from "@/context/PlayerContext";
import AudioBar from "@/components/Audiobar";
import QueryProvider from "@/context/QueryProvider";
import { AuthProvider } from "@/context/AuthContext";
import NextAuthProvider from "@/context/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <QueryProvider>
          <PlayerProvider>
            <div className="flex flex-col relative">
              <NextAuthProvider>
              <AuthProvider>
                <Sidebar />
                <Navbar />
                <main className="relative flex-1 min-w-0 mb-40 ">
                  <div className="flex lg:p-8 lg:ml-64 flex-col font-[family-name:var(--font-geist-sans)] ">
                    {children}
                  </div>
                </main>
              </AuthProvider>
              </NextAuthProvider>
            </div>
            <AudioBar />
          </PlayerProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
