import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
        <div className="flex ">
            <SideBar/>
          <main className="flex-1 md:p-8 md:ml-64 min-w-0 ">
            <Navbar />
              <div className="w-full z-0 top-5 md:top-10 flex flex-col font-[family-name:var(--font-geist-sans)] ">
                {children}
              </div>
          </main>
        </div>
      </body>
    </html>
  );
}
